- include: ../../../actions/tasks/module/module_configure.yml
  vars:
    package__php_mongodb__module__module_configure:
      title: "Configuring PHP MongoDb module - as specified by playbook"
      config: "{{ package__php_mongodb__setup__config }}"
