---
- include: ../../../../../package_management/apt/actions/tasks/packages/packages_install.yml
  vars:
    packages__apt__packages__packages_install:
      title: Installing Upstart
      latest: "{{ true }}"
      packages:
        - name: upstart
  when: fact_service.use_upstart | bool
