###
# ../../../../../package_management/apt/actions/tasks/packages/packages_install.yml
###
#
# Install APT Packages
#
###
#
# packages__apt__packages__packages_install:
#   title <string> ['Installing APT packages'] - Title of the operation
#   latest <bool> [true]                       - Should latest packages be installed
#   package_prefix <string> [""]               - Package prefix for all packages
#   packages:                                  - Packages to install
#    - name <string>                        - Name of a package
#      deb <string|omit> [omit]             - Debian package file
#      default_release <string|omit> [omit] - Default release string
#      force <bool:true|false} [true]       - Force install/remove
#      install_recommends <bool> [false]    - Should recommended packages be installed
#
###
- include: packages_manage.yml
  vars:
    packages__apt__packages__packages_manage:
      title: "{{ packages__apt__packages__packages_install.title | default('Installing APT packages') }}"
      state: "{% if packages__apt__packages__packages_install.latest | default(true) | bool %}latest{% else %}present{% endif %}"
      package_prefix: "{{ packages__apt__packages__packages_install.package_prefix | default('') | trim }}"
      packages: "{{ packages__apt__packages__packages_install.packages | mandatory }}"
