- include: ../../../actions/tasks/module/module_state.yml
  vars:
    package__php_xdebug__module__module_state:
      title: "Setting PHP xdebug state - as specified by playbook"
      state: "{{ package__php_xdebug__setup__state }}"
