---
- include: ../../../../../package_management/apt/actions/tasks/packages/packages_install.yml
  vars:
    packages__apt__packages__packages_install:
      title: Installing ImageMagick
      latest: "{{ true }}"
      packages:
        - name: imagemagick-common
        - name: imagemagick
