- include: ../../../actions/tasks/module/module_configure.yml
  vars:
    package__php_ldap__module__module_configure:
      title: "Configuring PHP ldap module - as specified by playbook"
      config: "{{ package__php_ldap__setup__config }}"
