- include: ../../../actions/tasks/module/module_state.yml
  vars:
    package__php_ctype__module__module_state:
      title: "Setting PHP ctype state - as specified by playbook"
      state: "{{ package__php_ctype__setup__state }}"
