---
- include: ../../../../../package/php/actions/tasks/module/module_configure.yml
  vars:
    package__php__module__module_configure:
      title: "Writting Symfony configuration module"
      module: "symfony"
      data:
        module_as_option_prefix: "{{ false }}"
        entries:
          - option: "date.timezone"
            value: "{{ fact_symfony.timezone }}"
          - option: "short_open_tag"
            value: "Off"
          - option: "magic_quotes_gpc"
            value: "Off"
          - option: "register_globals"
            value: "Off"
          - option: "session.auto_start"
            value: "Off"

- include: ../../../../../package/php/actions/tasks/module/module_state.yml
  vars:
    package__php__module__module_state:
      title: "Enabling Symfony configuration module"
      state: "enabled"
      modules:
        - module: "symfony"
