- include: ../../../actions/tasks/module/module_configure.yml
  vars:
    package__php_xmlrpc__module__module_configure:
      title: "Configuring PHP xmlrpc module - as specified by playbook"
      config: "{{ package__php_xmlrpc__setup__config }}"
