---
- include: ../../../../../package_management/apt/actions/tasks/packages/packages_install.yml
  vars:
    packages__apt__packages__packages_install:
      title: Installing Gitlab CI multi runner
      latest: "{{ true }}"
      packages:
        - name: gitlab-ci-multi-runner
