###
# ../../../../../package/php-dom/actions/tasks/module/module_state.yml
###
#
# Enable or disable PHP dom module
#
###
#
# package__php_dom__module__module_state:
#   title <string:"Setting PHP dom state"> - Title of the operation
#   state <"enabled"|"disabled">              - State of a module
#   modules:
#     - module <string> - module name
#
###

- include: ../../../../../package/php/actions/tasks/module/module_state.yml
  vars:
    package__php__module__module_state:
      title: "{{ package__php_dom__module__module_state.title | default('Setting PHP dom state') }}"
      state: "{{ package__php_dom__module__module_state.state | mandatory }}"
      modules:
        - module: dom
