---
- include: ../../../../../package_management/apt/actions/tasks/packages/packages_install.yml
  vars:
    packages__apt__packages__packages_install:
      title: Installing MongoDB
      latest: "{{ true }}"
      packages:
        - name: mongodb-org-tools
        - name: mongodb-org-mongos
        - name: mongodb-org-shell
        - name: mongodb-org-server
        - name: mongodb-org
