---
- name: Checking current MongoDB version
  script: "../../files/mongodb_version.sh {{ package__mongodb__package__mongodb_bin | quote }}"
  become: true
  register: result__package__mongodb__package__uninstall_version

- include: ../../../../../package_management/apt/actions/tasks/packages/packages_remove.yml
  vars:
    packages__apt__packages__packages_remove:
      title: Removing MongoDB
      packages:
        - name: mongodb-org
        - name: mongodb-org-server
        - name: mongodb-org-shell
        - name: mongodb-org-mongos
        - name: mongodb-org-tools
  when:     result__package__mongodb__package__uninstall_version.stdout | float != 0
        and result__package__mongodb__package__uninstall_version.stdout | float != package__mongodb__package__mongodb_version | float

- include: ../../../../../package_management/apt/actions/tasks/repositories/repositories_remove.yml
  vars:
    repositories__apt__repositories__repositories_remove:
      title: Removing MongoDB APT repositories
      repositories:
        - repo: "deb http://repo.mongodb.org/apt/{{ fact_os.distributor | lower }} {{ fact_os.codename | lower }}/mongodb-org/{{ result__package__mongodb__package__uninstall_version.stdout | float }} multiverse"
  when:     result__package__mongodb__package__uninstall_version.stdout | int != 0
        and result__package__mongodb__package__uninstall_version.stdout | float != package__mongodb__package__mongodb_version | float

