###
# ../../../../../package/rabbitmq/actions/tasks/users/users_manage.yml
###
#
# Manage RabbitMQ users
#
###
#
# package__rabbitmq__users__users_manage:
#   title <string> ["Managing RabbitMQ users"] - Title of the operation
#   state: <string:"absent"|"present">         - State of user
#   users:
#    - username <string>                   - Username
#      password <string|omit> [omit]       - Password of user (will use username if not specified)
#      vhost <string|omit> ["/"]           - vhost of RabbitMQ
#      priv <stirng> ['.*']                - Privilages. Privilages to grant for configure/read/write unless specified otherwise
#      configure_priv <string|omit> [omit] - Configure privilages
#      read_priv <string|omit> [omit]      - Read privilages
#      write_priv <string|omit> [omit]     - Write privilages 
#      tags <string> ["monitor"]           - Comma separated user tags
#
###
- name: "{{ package__rabbitmq__users__users_manage.title | default('Managing RabbitMQ users') }}"
  rabbitmq_user: user="{{ item.1.username | mandatory }}"
                 password="{{ item.1.password | default(omit) }}"
                 configure_priv="{{ item.1.configure_priv | default(item.1.priv | default('.*')) }}"
                 read_priv="{{ item.1.read_priv | default(item.1.priv | default('.*')) }}"
                 write_priv="{{ item.1.configure_priv | default(item.1.priv | default('.*')) }}"
                 state="{{ package__rabbitmq__users__users_manage.state }}"
                 tags="{{ item.1.tags | default('monitor') }}"
                 force="{{ true }}"
  with_indexed_items: "{{ package__rabbitmq__users__users_manage.users | default([]) }}"
  become: true
