###
# ../../../../../package/mysql-server/actions/tasks/databases/databases_add.yml
###
#
# Add MySQL databases
#
###
#
# package__mysql_server__databases__databases_add:
#   title <string> ["Adding MySQL databases"] - Title of the operation
#   databases:
#    - database <string>                     - database name
#      collation <string> [utf8_unicode_ci]  - database collation
#      encoding <string> [utf8]              - database encoding
#
###
- include: databases_manage.yml
  vars:
    package__mysql_server__databases__databases_manage:
      title: "{{ package__mysql_server__databases__databases_add.title | default('Adding MySQL databases') }}"
      state: present
      databases: "{{ package__mysql_server__databases__databases_add.databases | default([]) }}"

