###
# ../../../../../package/php-simplexml/actions/tasks/module/module_state.yml
###
#
# Enable or disable PHP simplexml module
#
###
#
# package__php_simplexml__module__module_state:
#   title <string:"Setting PHP simplexml state"> - Title of the operation
#   state <"enabled"|"disabled">              - State of a module
#   modules:
#     - module <string> - module name
#
###

- include: ../../../../../package/php/actions/tasks/module/module_state.yml
  vars:
    package__php__module__module_state:
      title: "{{ package__php_simplexml__module__module_state.title | default('Setting PHP simplexml state') }}"
      state: "{{ package__php_simplexml__module__module_state.state | mandatory }}"
      modules:
        - module: simplexml
