---
- include: ../../../../../package_management/apt/actions/tasks/packages/packages_install.yml
  vars:
    packages__apt__packages__packages_install:
      title: Installing ElasticSearch
      latest: "{{ true }}"
      packages:
        - name: elasticsearch

- name: Enabling ElasticSearch service at boot
  service: name="elasticsearch"
           enabled="{{ true }}"
  become: true
