---
- include:  ../../../../../system/service/actions/tasks/service_state/service_state_manage.yml
  vars:
    system__service__service_state__service_state_manage:
      title: "Stopping Rtail"
      state: "stopped"
      services:
        - name: "{{ system__service__package__service_prefix }}rtail"
