###
# ../../../../../package/php/actions/tasks/module/module_configure.yml
###
#
# Configures PHP module
#
###
#
# package__php__module__module_configure:
#   title <string:"Configuring PHP module"> - Title of the operation
#   module <string>                         - Name of a module
#   data:
#     module_as_option_prefix <bool|true> - Should module name be used as option prefix
#     entires:
#       - option <string>    - Option name
#         value <mixed:omit> - Value to set. {{ omit }} deletes entry
#
###
- name: "{{ package__php__module__module_configure.title | default('Configuring PHP module') }} (Reading priority info)"
  shell: "cat {{ (fact_php.mods_dir ~ '/' ~ package__php__module__module_configure.module | mandatory ~ '.ini') | quote }} | egrep \"^[[:space:]]*;[[:space:]]*priority[[:space:]]*=[[:space:]]*.*$\" -o | head -n 1"
  args:
    executable: /bin/bash
  become: true
  register: result__package__php__actions__module__module_configure__priority_line
  
- include: ../../../../../helper/ini/actions/tasks/ini/ini_write.yml
  vars:
    helper__ini__ini__write_ini:
      title: "{{ package__php__module__module_configure.title | default('Configuring PHP module') }}"
      file: "{{ fact_php.mods_dir }}/{{ package__php__module__module_configure.module | mandatory }}.ini"
      create: "{{ true | bool }}"
      must_exist: "{{ true | bool }}"
      attributes:
        owner: "root"
        group: "root"
        mode: 644
      values:
        true: 1
        false: 0
        null: ""
      data:
        sections:
          - section: "{{ package__php__module__module_configure.module | mandatory }}"
            option_name_prefix: "{% if package__php__module__module_configure.data.module_as_option_prefix | default(true) | bool %}{{ package__php__module__module_configure.module | mandatory }}.{% endif %}"
            entries: "{{ package__php__module__module_configure.data.entries | default([]) }}"

- name: "{{ package__php__module__module_configure.title | default('Configuring PHP module') }} (Restoring priority info)"
  lineinfile: dest="{{ fact_php.mods_dir }}/{{ package__php__module__module_configure.module | mandatory }}.ini"
              line="{{ result__package__php__actions__module__module_configure__priority_line.stdout }}"
              insertafter="[{{ package__php__module__module_configure.module | mandatory }}]"
              state="present"
  become: true
