###
# ../../../../../package/php-mysqlnd/actions/tasks/module/module_configure.yml
###
#
# Configures PHP mysqlnd module
#
###
#
# package__php_mysqlnd__module__module_configure:
#   title <string:"Configuring PHP mysqlnd module"> - Title of the operation
#   module <string>                                 - Name of a module
#   config:
#     - option <string>    - Option name
#       value <mixed:omit> - Value to set. {{ omit }} deletes entry
#
###
- include: ../../../../../package/php/actions/tasks/module/module_configure.yml
  vars:
    package__php__module__module_configure:
      title: "{{ package__php_mysqlnd__module__module_configure.title | default('Configuring PHP mysqlnd module') }}"
      module: "mysqlnd"
      data:
        module_as_option_prefix: true
        entries: "{{ package__php_mysqlnd__module__module_configure.config | default([]) }}"
