---
- include: ../../../../../package_management/apt/actions/tasks/keys/keys_add.yml
  vars:
    keys__apt__keys__keys_add:
      title: Adding GrayLog APT keys
      apt_keys:
        - url: "https://packages.graylog2.org/repo/debian/keyring.gpg"

- include: ../../../../../package_management/apt/actions/tasks/repositories/repositories_add.yml
  vars:
    repositories__apt__repositories__repositories_add:
      title: Adding GrayLog APT repositories
      repositories:
        - repo: "deb https://packages.graylog2.org/repo/debian/ stable 2.0"
