- include: ../../../../../system/service/actions/tasks/service_state/service_state_manage.yml
  vars:
    system__service__service_state__service_state_manage:
      title: Restarting Yaws
      state: restarted
      services:
        - name: yaws

- include: ../../../../../system/service/actions/tasks/service_state/service_state_manage.yml
  vars:
    system__service__service_state__service_state_manage:
      title: Stopping Yaws
      state: stopped
      services:
        - name: yaws

- include: ../../../../../system/service/actions/tasks/schedule_restart/schedule_restart_service.yml
  vars:
    system__service__schedule_restart__schedule_restart_service:
      title: Scheduling Yaws restart
      services:
        - service: yaws
