###
#
# package__mysql_server__users__users_add:
#   title <string> ["Adding MySQL users"] - Title of the operation
#   users:
#    - username <string>             - Username
#      password <string|omit> [omit] - Password of user (will use username if not specified)
#      host <string|omit> ["%"]      - Host part of mysql username
#      priv <stirng|omit> [omit]     - Privilages. Will grant all on "username" and "username_%" databases if not specified
#
###
- include: ../../../../../package/mysql-server/actions/tasks/users/users_add.yml
  vars:
    package__mysql_server__users__users_add:
      title: "Adding MySQL users - as specified by playbook"
      users: "{{ package__mysql_server__setup__users__add }}"
