---
- include: ../../../../../package_management/npm/actions/tasks/packages/packages_install.yml
  vars:
    packages__npm__packages__packages_install:
      title: Installing MailDev
      latest: "{{ true }}"
      packages:
        - name: maildev
