- include: ../../../actions/tasks/module/module_configure.yml
  vars:
    package__php_posix__module__module_configure:
      title: "Configuring PHP posix module - as specified by playbook"
      config: "{{ package__php_posix__setup__config }}"
