- include: ../../../actions/tasks/module/module_state.yml
  vars:
    package__php_xmlwriter__module__module_state:
      title: "Setting PHP xmlwriter state - as specified by playbook"
      state: "{{ package__php_xmlwriter__setup__state }}"
