- include: ../../../actions/tasks/module/module_state.yml
  vars:
    package__php_pdo_mysql__module__module_state:
      title: "Setting PHP pdo_mysql state - as specified by playbook"
      state: "{{ package__php_pdo_mysql__setup__state }}"
