- include: ../../../actions/tasks/module/module_configure.yml
  vars:
    package__php_gettext__module__module_configure:
      title: "Configuring PHP gettext module - as specified by playbook"
      config: "{{ package__php_gettext__setup__config }}"
