- include: ../../../actions/tasks/module/module_state.yml
  vars:
    package__php_gettext__module__module_state:
      title: "Setting PHP gettext state - as specified by playbook"
      state: "{{ package__php_gettext__setup__state }}"
