---
- include: ../../../../../package_management/apt/actions/tasks/packages/packages_install.yml
  vars:
    packages__apt__packages__packages_install:
      title: Installing Php
      latest: "{{ true }}"
      packages:
        - name: php-common
        - name: php-json
        - name: php-opcache
        - name: php-readline
        - name: php-cli
        - name: php-fpm
        - name: php
