###
# ../../../../../package/php-cgi/actions/tasks/php_ini/php_ini_configure.yml
###
#
# Configures PHP CGI ini
#
###
#
# package__php_cgi__php_ini__php_ini_configure:
#   title <string:"Configuring PHP CGI ini file"> - Title of the operation
#   data:
#     sections:
#        - seciton <string>            - Section name
#          option_name_prefix <string> - Prefix for option name
#          entires:
#            - option <string>    - Option name
#              value <mixed:omit> - Value to set. {{ omit }} deletes entry
#
###
- include: ../../../../../package/php/actions/tasks/php_ini/php_ini_configure.yml
  vars:
    package__php__php_ini__php_ini_configure:
      title: "{{ package__php_cgi__php_ini__php_ini_configure.title | default('Configuring PHP CGI ini file') }}"
      php: cgi
      data:
        sections: "{{ package__php_cgi__php_ini__php_ini_configure.data.sections | default([]) }}"
